import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export type MonthlyCompanyReportTemplate = 'executive' | 'compliance' | 'performance';

export type MonthlyCompanyReportInput = {
  companyName: string;
  monthLabel: string;
  generatedAt: Date;
  generatedBy: string;
  template: MonthlyCompanyReportTemplate;
  checksCompleted: number;
  defectsReported: number;
  defectsResolved: number;
  resolutionRate: number | null;
  openDefects: number;
  criticalOpenDefects: number;
  inactivityDays: number | null;
  summaryNote?: string;
};

const BLACK: [number, number, number] = [0, 0, 0];
const BLUE: [number, number, number] = [66, 133, 244];
const GRAY: [number, number, number] = [70, 70, 70];
const LIGHT_GRAY: [number, number, number] = [232, 236, 242];

type PdfRenderOptions = {
  logoDataUrl?: string;
};

function buildReferenceId(input: MonthlyCompanyReportInput): string {
  const stamp = input.generatedAt.toISOString().replace(/[-:.TZ]/g, '').slice(0, 12);
  return `STP-MONTHLY-${stamp}`;
}

function buildFilename(input: MonthlyCompanyReportInput): string {
  const filenameCompany = input.companyName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  const filenameMonth = input.monthLabel.toLowerCase().replace(/\s+/g, '-');
  return `stp-monthly-report-${filenameCompany}-${filenameMonth}.pdf`;
}

function renderReportDoc(input: MonthlyCompanyReportInput, options: PdfRenderOptions = {}): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  let y = margin;
  const referenceId = buildReferenceId(input);

  if (options.logoDataUrl) {
    try {
      doc.addImage(options.logoDataUrl, 'PNG', margin, y - 1, 24, 10);
    } catch {
      // If logo image parsing fails, keep rendering with text branding.
    }
  } else {
    doc.setFillColor(...BLUE);
    doc.roundedRect(margin, y - 1, 24, 10, 1.8, 1.8, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(255, 255, 255);
    doc.text('STP', margin + 12, y + 5.2, { align: 'center' });
  }

  doc.setDrawColor(...LIGHT_GRAY);
  doc.line(margin, y + 11, pageWidth - margin, y + 11);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BLACK);
  doc.setFontSize(18);
  doc.text('Monthly Company Performance Report', margin + 28, y + 3);
  y += 7;

  doc.setFontSize(9);
  doc.setTextColor(...BLUE);
  doc.text('Stock Track PRO | Admin Evidence Export', margin + 28, y + 1);
  y += 8;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY);
  doc.setFontSize(10);
  doc.text(`Company: ${input.companyName}`, margin, y);
  y += 4.5;
  doc.text(`Reporting month: ${input.monthLabel}`, margin, y);
  y += 4.5;
  doc.text(`Template: ${input.template.charAt(0).toUpperCase()}${input.template.slice(1)}`, margin, y);
  y += 4.5;
  doc.text(`Generated by: ${input.generatedBy}`, margin, y);
  y += 4.5;
  doc.text(`Generated at: ${input.generatedAt.toLocaleString('en-GB')}`, margin, y);
  y += 4.5;
  doc.text(`Reference: ${referenceId}`, margin, y);
  y += 8;

  autoTable(doc, {
    startY: y,
    head: [['KPI', 'Value']],
    body: [
      ['Checks completed', String(input.checksCompleted)],
      ['Defects reported', String(input.defectsReported)],
      ['Defects resolved', String(input.defectsResolved)],
      ['Resolution rate', input.resolutionRate === null ? 'N/A' : `${input.resolutionRate}%`],
      ['Open defects (end of month)', String(input.openDefects)],
      ['Critical open defects', String(input.criticalOpenDefects)],
      ['Days since last check', input.inactivityDays === null ? 'No data' : `${input.inactivityDays} days`],
    ],
    styles: { fontSize: 10, textColor: BLACK },
    headStyles: { fillColor: BLUE, textColor: 255, fontStyle: 'bold' },
    margin: { left: margin, right: margin },
  });

  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BLACK);
  doc.setFontSize(12);
  doc.text('Value Summary', margin, y);
  y += 6;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY);
  doc.setFontSize(10);
  const defaultSummary =
    `This month, ${input.companyName} completed ${input.checksCompleted} checks, reported ${input.defectsReported} defects, and resolved ${input.defectsResolved}. ` +
    `Use this report to evidence proactive maintenance control and defect closure performance with stakeholders.`;
  const wrapped = doc.splitTextToSize(input.summaryNote || defaultSummary, pageWidth - margin * 2);
  doc.text(wrapped, margin, y);
  y += wrapped.length * 4.3 + 8;

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BLACK);
  doc.setFontSize(11);
  doc.text('Metric Definitions', margin, y);
  y += 5.5;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY);
  doc.setFontSize(9);
  const definitions = [
    'Checks completed: number of vehicle inspections recorded within the selected month.',
    'Defects reported: number of defects raised within the selected month.',
    'Defects resolved: number of defects marked resolved within the selected month.',
    'Resolution rate: defects resolved in month divided by defects reported in month.',
  ];
  definitions.forEach((line) => {
    const lineWrapped = doc.splitTextToSize(`- ${line}`, pageWidth - margin * 2);
    doc.text(lineWrapped, margin, y);
    y += lineWrapped.length * 4 + 1;
  });

  const footerY = pageHeight - 18;
  doc.setDrawColor(...LIGHT_GRAY);
  doc.line(margin, footerY - 4, pageWidth - margin, footerY - 4);
  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text(
    'Confidential - prepared for operational review. For full evidential pack, retain source inspection and defect records.',
    margin,
    footerY
  );
  doc.text(`Stock Track PRO - ${referenceId}`, margin, footerY + 4);

  return doc;
}

export async function exportAdminMonthlyCompanyReportPDF(input: MonthlyCompanyReportInput): Promise<void> {
  let logoDataUrl: string | undefined;
  try {
    const logoResponse = await fetch('/logo.png');
    if (logoResponse.ok) {
      const blob = await logoResponse.blob();
      logoDataUrl = await new Promise<string>((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(String(reader.result));
        reader.onerror = reject;
        reader.readAsDataURL(blob);
      });
    }
  } catch {
    // If logo cannot be loaded on client, PDF still renders with text branding.
  }

  const doc = renderReportDoc(input, { logoDataUrl });
  doc.save(buildFilename(input));
}

export function buildAdminMonthlyCompanyReportPdfBytes(
  input: MonthlyCompanyReportInput,
  options: PdfRenderOptions = {}
): Uint8Array {
  const doc = renderReportDoc(input, options);
  const arrayBuffer = doc.output('arraybuffer');
  return new Uint8Array(arrayBuffer);
}
