import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export type MonthlyCompanyReportTemplate = 'executive' | 'compliance' | 'performance';

export type MonthlyCompanyReportInput = {
  companyName: string;
  monthLabel: string;
  generatedAt: Date;
  generatedBy: string;
  template: MonthlyCompanyReportTemplate;
  checksCompleted: number;
  defectsReported: number;
  defectsResolved: number;
  resolutionRate: number | null;
  openDefects: number;
  criticalOpenDefects: number;
  inactivityDays: number | null;
  summaryNote?: string;
};

const BLACK: [number, number, number] = [0, 0, 0];
const BLUE: [number, number, number] = [66, 133, 244];
const GRAY: [number, number, number] = [70, 70, 70];

export function exportAdminMonthlyCompanyReportPDF(input: MonthlyCompanyReportInput): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  let y = margin;

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BLACK);
  doc.setFontSize(18);
  doc.text('Monthly Company Performance Report', margin, y);
  y += 7;

  doc.setFontSize(10);
  doc.setTextColor(...BLUE);
  doc.text('Stock Track PRO Admin Panel', margin, y);
  y += 6;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY);
  doc.text(`Company: ${input.companyName}`, margin, y);
  y += 4.5;
  doc.text(`Reporting month: ${input.monthLabel}`, margin, y);
  y += 4.5;
  doc.text(`Template: ${input.template}`, margin, y);
  y += 4.5;
  doc.text(`Generated by: ${input.generatedBy}`, margin, y);
  y += 4.5;
  doc.text(`Generated at: ${input.generatedAt.toLocaleString('en-GB')}`, margin, y);
  y += 8;

  autoTable(doc, {
    startY: y,
    head: [['KPI', 'Value']],
    body: [
      ['Checks completed', String(input.checksCompleted)],
      ['Defects reported', String(input.defectsReported)],
      ['Defects resolved', String(input.defectsResolved)],
      ['Resolution rate', input.resolutionRate === null ? 'N/A' : `${input.resolutionRate}%`],
      ['Open defects (end of month)', String(input.openDefects)],
      ['Critical open defects', String(input.criticalOpenDefects)],
      ['Days since last check', input.inactivityDays === null ? 'No data' : `${input.inactivityDays} days`],
    ],
    styles: { fontSize: 10, textColor: BLACK },
    headStyles: { fillColor: BLUE, textColor: 255, fontStyle: 'bold' },
    margin: { left: margin, right: margin },
  });

  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BLACK);
  doc.setFontSize(12);
  doc.text('Value Summary', margin, y);
  y += 6;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GRAY);
  doc.setFontSize(10);
  const defaultSummary =
    `This month, ${input.companyName} completed ${input.checksCompleted} checks, reported ${input.defectsReported} defects, and resolved ${input.defectsResolved}. ` +
    `Use this report to evidence proactive maintenance control and defect closure performance with stakeholders.`;
  const wrapped = doc.splitTextToSize(input.summaryNote || defaultSummary, pageWidth - margin * 2);
  doc.text(wrapped, margin, y);

  const filenameCompany = input.companyName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  const filenameMonth = input.monthLabel.toLowerCase().replace(/\s+/g, '-');
  doc.save(`stp-monthly-report-${filenameCompany}-${filenameMonth}.pdf`);
}
