/** Labels for Blood/Organ inspection checks — mirrored from the mobile template. */

export const BLOOD_ORGAN_PHOTO_LABELS: Record<string, string> = {
  front: 'Front Exterior',
  rear: 'Rear Exterior',
  driver_side: 'Driver Side',
  passenger_side: 'Passenger Side',
  interior: 'Interior / Load Area',
  mileage: 'Mileage / Odometer',
};

export const BLOOD_ORGAN_SECTION_ORDER = [
  'exterior',
  'lights',
  'tyres',
  'fluids',
  'in_cab',
  'medical',
  'cleanliness',
] as const;

export const BLOOD_ORGAN_SECTION_TITLES: Record<string, string> = {
  exterior: 'Exterior Checks',
  lights: 'Lights and Emergency Equipment',
  tyres: 'Tyres and Wheels',
  fluids: 'Fluids and Mechanical',
  in_cab: 'In-Cab Checks',
  medical: 'Medical Transport Equipment',
  cleanliness: 'Cleanliness and Readiness',
};

export const BLOOD_ORGAN_CHECK_LABELS: Record<string, { title: string; sectionId: string }> = {
  ext_bodywork: { title: 'Bodywork and exterior condition', sectionId: 'exterior' },
  ext_windscreen_glass: { title: 'Windscreen and glass', sectionId: 'exterior' },
  ext_mirrors: { title: 'Mirrors', sectionId: 'exterior' },
  ext_number_plates: { title: 'Number plates', sectionId: 'exterior' },
  ext_wipers_washers: { title: 'Wipers and washers', sectionId: 'exterior' },
  ext_doors_secure: { title: 'Doors, bonnet and boot secure', sectionId: 'exterior' },
  ext_fluid_leaks: { title: 'Visible fluid leaks', sectionId: 'exterior' },
  lights_head_side: { title: 'Headlights and sidelights', sectionId: 'lights' },
  lights_brake: { title: 'Brake lights', sectionId: 'lights' },
  lights_indicators: { title: 'Indicators and hazard lights', sectionId: 'lights' },
  lights_reverse: { title: 'Reverse lights', sectionId: 'lights' },
  lights_plate: { title: 'Registration plate lights', sectionId: 'lights' },
  lights_blue: { title: 'Blue warning lights', sectionId: 'lights' },
  lights_siren: { title: 'Siren', sectionId: 'lights' },
  lights_beacon: { title: 'Warning beacon', sectionId: 'lights' },
  tyre_tread: { title: 'Tyre tread and general condition', sectionId: 'tyres' },
  tyre_damage: { title: 'No cuts, bulges or exposed cords', sectionId: 'tyres' },
  tyre_inflation: { title: 'Tyres appear correctly inflated', sectionId: 'tyres' },
  tyre_wheel_nuts: { title: 'Wheels and wheel nuts secure', sectionId: 'tyres' },
  tyre_spare_or_kit: { title: 'Spare wheel or tyre repair kit present where applicable', sectionId: 'tyres' },
  fluid_oil: { title: 'Engine oil level', sectionId: 'fluids' },
  fluid_coolant: { title: 'Coolant level', sectionId: 'fluids' },
  fluid_screenwash: { title: 'Screenwash level', sectionId: 'fluids' },
  fluid_dash_warnings: { title: 'Dashboard warning lights', sectionId: 'fluids' },
  fluid_fuel_battery: { title: 'Fuel or battery charge sufficient', sectionId: 'fluids' },
  fluid_steering: { title: 'Steering operating correctly', sectionId: 'fluids' },
  fluid_mech_issues: { title: 'No visible leaks or unusual mechanical issues', sectionId: 'fluids' },
  cab_service_brake: { title: 'Service brake', sectionId: 'in_cab' },
  cab_parking_brake: { title: 'Parking brake', sectionId: 'in_cab' },
  cab_seatbelts: { title: 'Seatbelts', sectionId: 'in_cab' },
  cab_horn: { title: 'Horn', sectionId: 'in_cab' },
  cab_heating: { title: 'Heating and demisting', sectionId: 'in_cab' },
  cab_seat_controls: { title: 'Driver seat and controls', sectionId: 'in_cab' },
  cab_comms: { title: 'Communication equipment', sectionId: 'in_cab' },
  cab_satnav: { title: 'Sat-nav or route device', sectionId: 'in_cab' },
  med_container_present: { title: 'Medical transport container present', sectionId: 'medical' },
  med_container_secure: { title: 'Transport container secure', sectionId: 'medical' },
  med_container_clean: { title: 'Transport container clean', sectionId: 'medical' },
  med_container_undamaged: { title: 'Transport container undamaged', sectionId: 'medical' },
  med_coolbox_present: { title: 'Cool box present where required', sectionId: 'medical' },
  med_coolbox_suitable: { title: 'Cool box clean and suitable for use', sectionId: 'medical' },
  med_temp_present: { title: 'Temperature monitor present where required', sectionId: 'medical' },
  med_temp_operational: { title: 'Temperature monitor operational', sectionId: 'medical' },
  med_load_restraints: { title: 'Load restraints secure', sectionId: 'medical' },
  med_equipment_stored: { title: 'Medical transport equipment securely stored', sectionId: 'medical' },
  med_paperwork: { title: 'Required paperwork or emergency contacts available', sectionId: 'medical' },
  clean_cab: { title: 'Cab clean', sectionId: 'cleanliness' },
  clean_load_area: { title: 'Load area clean', sectionId: 'cleanliness' },
  clean_transport_equipment: { title: 'Transport equipment clean', sectionId: 'cleanliness' },
  clean_no_contamination: { title: 'No visible contamination', sectionId: 'cleanliness' },
  clean_waste: { title: 'Waste removed', sectionId: 'cleanliness' },
  clean_ready: { title: 'Vehicle ready for operational use', sectionId: 'cleanliness' },
};

export const CAR_VAN_WALKAROUND_LABELS: Record<string, string> = {
  external_condition: 'External Condition',
  tyres_wheels: 'Tyres & Wheels',
  fluid_levels: 'Fluid Levels',
  load_security: 'Load Security',
  in_cab_checks: 'In-Cab Checks',
  final_confirm: 'Final declaration',
};
